spring.application.name=gym-persona-api

spring.datasource.url=jdbc:postgresql://localhost:5432/persona_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:dev.passN18}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=3003
spring.jpa.open-in-view=false